# Generated by Django 4.1.9 on 2024-05-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='password',
        ),
        migrations.AddField(
            model_name='photographer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photographer', to='core.user'),
            preserve_default=False,
        ),
    ]
